import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from "react-bootstrap/Container";
import AppHeader from "@/components/app.header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <AppHeader />
        <Container className="my-3">
          <main>{children}</main>
        </Container>
        <footer>
          <div className="text-center py-2" style={{ backgroundColor: "#f8f9fa" }}>
            <p className="mb-0">© 2026 My Next.js App. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}


